server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin

      routes:

        # AUTH SERVICE
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/login,/auth/register

        # AUTH SWAGGER
        - id: auth-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs


        # USER SERVICE
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        # SCHEDULING SERVICE
        - id: scheduling-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/appointments/**

        # NOTIFICATION SERVICE
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**

        # AI SERVICE
        - id: ai-service
          uri: http://localhost:8085
          predicates:
            - Path=/ai/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs

jwt:
  secret: my-super-secret-key-for-jwt-validation-123456

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG